---
- name: Install Neovim
  homebrew:
    name: nvim
    state: present

- name: Clone Neovim Config Repository
  git:
    repo: "https:github.com/nxstynate/config_files"
    dest: "~/."
    version: "main" # or any other branch/tag
    force: yes # Use force to ensure the latest version is pulled
  register: git_clone

- name: Copy Neovim Configuration Files
  copy:
    src: "../../../dotfiles/.config/nvim/*"
    dest: "~/.config/nvim/."
    mode: "0644"
  when: git_clone.changed
